### ISSUE TITLE
Automate copying of S3 media folder for a particular organisation from prod to pre-release

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-infra#30]
- automate this via circle ci
- ensure there are no delete operations used anywhere in this automation (use rename if required)

**Comment by mahalakshme** [comment]
@petmongrels if we do this we also need to change the url in the db accordingly

@himeshr @1t5j0y you can find the best way to do the same.

**Comment by petmongrels** [comment]
@mahalakshme it seems this has been take care on the code of etl. when signing the urls the code, transforms the URL from prod to pre-release. it is currently working for goonj after copying the folder.

**Comment by himeshr** [comment]
We should no longer attempt to do this, because, there is a functioning work around for us already, which is to configure AWS AccessKeys used in prod and prerelease environments to have access to each-other's Media buckets in S3.

In future, we can think of storing relative url paths in observations and entities and use S3 config specific to env / org to generate the absolute path, which would be a capability that could be configured at first time setup of an environment.
